name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          # The AWS region where your ECR repository is located
          region: ap-south-1
        env:
          AWS_ACCESS_KEY_ID: 'AKIA5FTZESLL2R3WYKBH'
          AWS_SECRET_ACCESS_KEY: 'n070GY+zg9Ye/zWbmSCEPcVFt6HUWyUdasRwMoQk'

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: '905418412759.dkr.ecr.ap-south-1.amazonaws.com'
          ECR_REPOSITORY: 'hello-world-app'
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to ECS
        env:
          AWS_REGION: 'ap-south-1'
          AWS_ACCESS_KEY_ID: 'AKIA5FTZESLL2R3WYKBH'
          AWS_SECRET_ACCESS_KEY: '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'
          ECS_CLUSTER: 'hello-world-cluster'
          ECS_SERVICE: 'hello-world-service'
          IMAGE_TAG: ${{ github.sha }}
          ECR_REGISTRY: '905418412759.dkr.ecr.ap-south-1.amazonaws.com'
          ECR_REPOSITORY: 'hello-world-app'
        run: |
          ecs-deploy -r $AWS_REGION -c $ECS_CLUSTER -n $ECS_SERVICE -i $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
